version: '3.8'

services:
  apollo-server:
    image: library-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 4000:4000
    secrets:
      - MONGODB_URI
      - JWT_SECRET
      - PORT
    container_name: apollo-server-dev
secrets:
  MONGODB_URI:
    file: ./mongo_url.txt
  JWT_SECRET:
    file: ./jwt_secret.txt
  PORT:
    file: ./port_secret.txt
