version: '3.8'

services:
  app:
    image: library-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:80
    container_name: library-frontend
